### ISSUE TITLE
parse stdout malformed parameters:missing equals when using href=

### ISSUE THREAD

**Issue by aaronedell** [matryer/xbar#667] opened 2021-03-26 21:16 UTC
Here is the troublesome bit of code

`fmt.Println("VaccinateCA")
	fmt.Println("---")

	for i := 0; i < len(g.Content); i++ {
		if g.Content[i].County == "Contra Costa County" && g.Content[i].Has == 1 {
			fmt.Println("Name: " + g.Content[i].Name)
			fmt.Println("Availabliity Info: ")
			for k := 0; k < len(g.Content[i].Availability); k++ {
				fmt.Println(g.Content[i].Availability[k])
			}
			if len(g.Content[i].ClickURL) != 0 {
				fmt.Println("Make Appointment | href=" + g.Content[i].ClickURL[0])
			}
			fmt.Println("---")
		}
	}`

In the terminal it prints 
`Make Appointment | href=https://www.cvs.com/immunizations/covid-19-vaccine`

But when its in Xbar I get the error listed as the title. If I comment out the href part of my code, it works (obviously without the clickable text).

**Comment by leaanthony** [comment] 2021-03-27 04:29
Hi. I'm unable to reproduce this. Using the following script, I get redirected to the CVS site:

![image](https://user-images.githubusercontent.com/1943904/112709889-171e2680-8f11-11eb-9f00-2b02958e81fd.png)

**Comment by matryer** [comment] 2021-03-28 08:35
@aaronedell what version of xbar are you running?

**Comment by magicus** [comment] 2021-03-29 09:35
@aaronedell Are you sure your code is correct? Do `g` have a proper value? Try removing the `|` to verify that the URL are indeed fetched as supposed even when running in xbar. (Then you will see the href= argument in the xbar menu)

**Comment by aaronedell** [comment] 2021-03-29 17:51
I mean, I can't be sure its correct but when the same code outputs to the
terminal, the output is correct with the | href=http:... etc. I do know
something is wrong with the way its putting the value in because if I just
hardcode in a URL it works. What happens if it prints | href=null or
something that isn't a proper URL? Mr. Ryer helped me by suggesting I
change the code from fmt.Println("Make Appointment | href="+
g.Content[i].ClickURL[0]) to fmt.Printf("Make Appointment | href=%q\n",
g.Content[i].ClickURL[0])

It works now - but I don't know why. xbar version is 2.0.33

**Comment by matryer** [comment] 2021-04-05 10:24
I think the URL may have contained spaces or something, so quoting it has fixed it. Closing for now. Thanks all.

**Closed by matryer** 2021-04-05 10:24 UTC

**Comment by leaanthony** [comment] 2021-04-05 20:58
Looks like a \n issue to me. Echo will add one so my script worked. Printf requires an explicit one. Just a guess!
