### ISSUE TITLE
xbar closing when importing plugin from browser

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [matryer/xbar#679] opened 2021-03-31 23:10 UTC
I just started to use xbar but whenever I click off of xbar or ALT tab out of xbar it closes and says The application "xbar.app" is not open anymore. I have tried opening from the menu bar, dock, launchpad, and finder, but no luck. I've also tried to restart my system and no luck there. I don't have any plugins installed either.
<img width="1280" alt="Screen Shot 2021-03-31 at 7 02 07 PM" src="https://user-images.githubusercontent.com/70828596/113221837-ca5d8700-9253-11eb-8f9b-9f8c89fa1fb0.png">

**Comment by Isaiah-Hamilton** [comment] 2021-03-31 23:18
Update I've tried to quit the application but it still does that same thing.

**Comment by leaanthony** [comment] 2021-03-31 23:56
Cannot reproduce this. What OS/xbar version? What plugins do you have?

**Comment by Isaiah-Hamilton** [comment] 2021-04-01 00:00
I'm running macOS 11.2.3, xbar version v2.0.38-beta, and I have only one plugin installed called Weather - OpenWeatherMap

**Comment by Isaiah-Hamilton** [comment] 2021-04-01 01:51
I have some more info on how the error occurs. When I go to the website and click on any plugin the error shows up and after pressing ok the app hides and the plugin never loads. Also as you can see in the video the menubar icon is missing. The version of xbar that I'm using is v2.0.38-beta, macOS 11.2.3, and one plugin called Weather - OpenWeatherMap.

https://user-images.githubusercontent.com/70828596/113231888-259a7400-926a-11eb-8567-7675b709336a.mov

**Comment by matryer** [comment] 2021-04-02 07:49
@Isaiah-Hamilton thanks for the great report - we'll look into this.

**Comment by matryer** [comment] 2021-04-02 07:54
@Isaiah-Hamilton Can you do my a favour? Would you be able to install xbar again (download it and drag it into your Application folder) to see if this fixes it?

I want to see if the auto-update process causes this.

1. Install a previous (not latest) release of xbar from https://github.com/matryer/xbar/releases
2. Try to use the **Open in xbar app** option
3. Go through the update process
4. Try to use the **Open in xbar app** option again

**Comment by Isaiah-Hamilton** [comment] 2021-04-02 13:53
I did as you said, but still am getting the same error. I installed v2.0.37, v2.0.38, v2.0.38, v.1.10.0, and they all don't work for some reason. I might be installing it wrong so here's a video of me installing it for more detail. When I installed older versions and newer versions of xbar. I made sure to close xbar before installing xbar, but it wouldn't close. Like last time the menubar icon doesn't show, and the menubar actions don't work either.

https://user-images.githubusercontent.com/70828596/113420676-b9b62980-9397-11eb-8d23-44be8d1707f4.mov

**Comment by matryer** [comment] 2021-04-03 07:30
@Isaiah-Hamilton no, you're doing it right. What a strange error you're seeing, will investigate.

**Comment by leaanthony** [comment] 2021-04-03 10:25
Seems like this is not a new problem for MacOS: https://discussions.apple.com/thread/7465484

**Comment by matryer** [comment] 2021-04-05 08:17
@leaanthony I wonder if fixing the bundle identifier #686 will help here? Otherwise, we should look to the way we're updating the app.

**Comment by leaanthony** [comment] 2021-04-05 09:44
Yeah good call. Let's see what the feedback is.

**Comment by matryer** [comment] 2021-04-05 10:23
@Isaiah-Hamilton the latest release fixes the bundle identifier, please let me know if you still see this behaviour with this and future releases.

**Comment by Isaiah-Hamilton** [comment] 2021-04-05 15:19
Thank you so much @matryer and @leaanthony. Its work perfectly, and can't wait to install some plugins, and I will let you know if I run into any more problems.

**Comment by matryer** [comment] 2021-04-06 09:22
Thanks @Isaiah-Hamilton. Closing now.

**Closed by matryer** 2021-04-06 09:22 UTC

**Comment by tarunbhardwaj** [comment] 2021-05-06 04:55
Still facing same issue. following are the details.

xbar version: v2.0.42-beta
OS: MacOS Big Sur 11.1 - M1

Error:
![image](https://user-images.githubusercontent.com/3259423/117243409-d8a35200-ae54-11eb-829a-bd168b1fc71d.png)


* Can't open any `xbar://app.xbarapp.com/...` url.
* Get same error on opening app again.

Last but not the least, xbar is one of the apps I can't live without. Thank you for all the hard work.
