### ISSUE TITLE
README says Catalina or higher, but doesn't start on 10.15.7

### ISSUE THREAD

**Issue by shepazon** [matryer/xbar#612] opened 2021-03-08 20:57 UTC
Although the readme on GitHub says xbar works on macOS Catalina or newer (>= 10.15), my laptop with 10.15.7 won't start xbar, saying that it requires 11.0 or later.

**Comment by matryer** [comment] 2021-03-08 21:25
@shepazon Can you try this one please? https://github.com/matryer/xbar/releases/tag/v2.0.7-beta

**Comment by shepazon** [comment] 2021-03-08 21:29
> @shepazon Can you try this one please? [`v2.0.7-beta` (release)](https://github.com/matryer/xbar/releases/tag/v2.0.7-beta)

I get the same error with this build.

**Comment by adrianmester** [comment] 2021-03-08 21:46
same here

> You have macOS 10.15.7. The application requires macOS 11.0 or later.

**Comment by ianfoo** [comment] 2021-03-09 05:30
I can confirm I'm able to build and run this app on 10.15.7, so it sounds like perhaps there's something in the way it's being assembled/packaged that restricts the versioning, rather than a technical limitation. 🤔

**Comment by leaanthony** [comment] 2021-03-09 07:04
Like @ianfoo - can confirm the app runs on Catalina (just run the binary in the package) so it looks like we just need to adjust the signing of the app.

**Comment by leaanthony** [comment] 2021-03-09 07:10
<img width="1290" alt="Screen Shot 2021-03-09 at 6 08 33 pm" src="https://user-images.githubusercontent.com/1943904/110432014-b4e8b780-8102-11eb-8e43-c6ff0b303916.png">

**Comment by matryer** [comment] 2021-03-09 13:11
@shepazon Can you please try the the [latest release](http://github.com/matryer/xbar/releases/latest) to see if it will run for you now?

**Comment by shepazon** [comment] 2021-03-09 13:21
Same error with 2.0.12-beta. But I can confirm that it will run if I start it from the shell prompt.

**Comment by matryer** [comment] 2021-03-10 15:10
@shepazon is the latest release still doing this?

**Comment by shepazon** [comment] 2021-03-10 15:14
@matryer Yep. Still doing it in 2.0.19-beta. Sorry. :)

**Comment by matryer** [comment] 2021-03-10 15:30
@shepazon Do you have a screenshot of what message you're getting?

**Comment by shepazon** [comment] 2021-03-10 15:33
@matryer Sure do:

![xbar-startup-error](https://user-images.githubusercontent.com/74020957/110654219-f2ddee00-818b-11eb-8751-f3ef1e97473c.png)

**Comment by matryer** [comment] 2021-03-10 15:46
@shepazon can you try this for me and let me know if it's any better? Thanks so much for your help on this.

[xbar.v2.0.19-beta-3-g6958a33a.tar.gz](https://github.com/matryer/xbar/files/6117097/xbar.v2.0.19-beta-3-g6958a33a.tar.gz)

**Comment by matryer** [comment] 2021-03-10 16:03
@shepazon for my sanity, I wonder if you could look inside the `xbar.app` in `Contents/MacOS/Info.plist` and let paste the contents here?

**Comment by shepazon** [comment] 2021-03-10 17:39
Sure. It looks fine to me though:

```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
	<key>CFBundlePackageType</key><string>APPL</string>
	<key>CFBundleName</key><string>xbar</string>
	<key>CFBundleExecutable</key><string>xbar</string>
	<key>CFBundleIdentifier</key><string>xbar.v2.0.19-beta-3-g6958a33a</string>
	<key>CFBundleVersion</key><string>v2.0.19-beta-3-g6958a33a</string>
	<key>CFBundleURLTypes</key>
    	<array>
    		<dict>
    			<key>CFBundleTypeRole</key>
    			<string>Viewer</string>
    			<key>CFBundleURLSchemes</key>
    			<array>
    				<string>xbar</string>
    			</array>
    		</dict>
    	</array>
	<key>CFBundleGetInfoString</key><string>Put anything into your macOS menu bar (https://xbarapp.com)</string>
	<key>CFBundleShortVersionString</key><string>v2.0.19-beta-3-g6958a33a</string>
	<key>CFBundleIconFile</key><string>iconfile</string>
	<key>NSHighResolutionCapable</key><string>true</string>
	<key>LSMinimumSystemVersion</key><string>10.15.0</string>
	<key>NSHumanReadableCopyright</key><string>Copyright 2021 Mat Ryer and the xbar contributors</string>
</dict></plist>
```

**Comment by matryer** [comment] 2021-03-10 17:40
Yeah, same. OK, the search continues.

**Comment by kubacupisz** [comment] 2021-03-10 18:26
I just ran into the same issue. I checked the latest beta binary in `otool -l` and it gives `minos 11.0`, so that is likely the culprit. Hope this helps!

**Comment by matryer** [comment] 2021-03-10 18:33
Thanks @kubacupisz - that may help. @leaanthony and I will track this down.

**Comment by manojkarthick** [comment] 2021-03-12 03:51
Just wanted to add that I'm getting the same error as others using the `v2.0.24-beta` on Catalina `10.15.6` as well. It works great on Big Sur. Thanks a lot for building this awesome app!

**Comment by matryer** [comment] 2021-03-12 12:48
@manojkarthick @kubacupisz @shepazon - we think we have a fix for this, please try the [latest release](https://github.com/matryer/xbar/releases/latest).

**Comment by kubacupisz** [comment] 2021-03-12 13:08
v2.0.25-beta works perfectly, thanks @matryer and @leaanthony!

**Comment by matryer** [comment] 2021-03-12 14:13
Being optimistic and closing this. Thanks for reporting everyone, please keep them coming.

**Closed by matryer** 2021-03-12 14:13 UTC
Labels: bug

**Comment by shepazon** [comment] 2021-03-12 17:07
"This house is clean!"

**Comment by sainathadapa** [comment] 2021-06-05 08:13
I'm on BigSur 11.4 and get this error for 2.0.42 beta version. See the attached screenshot. 
<img width="247" alt="Screenshot 2021-06-05 at 1 43 34 PM" src="https://user-images.githubusercontent.com/4915751/120884990-07534a80-c604-11eb-8fe9-2154229574e4.png">
