### ISSUE TITLE
Nested submenus prevent previous submenu link to be opened

### ISSUE THREAD

**Issue by ggrelet** [matryer/xbar#637] opened 2021-03-15 16:13 UTC
In python I noticed a strange behavior with clickable links (which was all right with BitBar).

## Suppose the following piece of python code (working as expected):
```python
#!/usr/bin/env PYTHONIOENCODING=UTF-8 /usr/bin/python3

print("bug test")
print('---')
print("google.com | href='https://google.com/'")
```
It simply adds a `bug test` in your menu bar and the drop down menu simply shows a `google.com` which you can click on and gets you to https://google.com/ on the default browser of your machine. **Everything works as expected.**

## Now, suppose the following code (not working as expected):
```python
#!/usr/bin/env PYTHONIOENCODING=UTF-8 /usr/bin/python3

print("bug test")
print('---')
print("google.com | href='https://google.com/'")
print("--yahoo.com | href='https://yahoo.com/'")
```
It simply adds a `bug test` in your menu bar and the drop down menu simply shows a `google.com` with a `yahoo.com` submenu (_expected and working_). In theory both menu and submenu should be clickable (_expected_). The first one goes to https://google.com/ (_expected, **not** working_) the second one goes to https://yahoo.com/ (_expected, working_).

**The actual behavior is that only the second-level menu is clickable (https://yahoo.com/) not the first one (https://google.com/).** Both should be clickable.

I've also tried with a third submenu (redirecting to https://bing.com/) and the second submenu (https://yahoo.com/) becomes unclickable. **Quick conclusion, it appears that only the latest submenu in a chain of submenus can be clicked on**.

Hope my problem description makes sense. Let me know if I should rephrase anything.

```
macOS 10.15.7
xbar 2.0.27-beta17
Python v3.8.2
```

**Comment by matryer** [comment] 2021-03-15 21:42
Hey @ggrelet thanks for the great question. If I understood you correctly, I think the behaviour you're describing is what I would expect to happen.

Given the following xbar code:

```
top1 
top2 
top3 >
--child1 >
----grandchild1
----grandchild2
--child2 
```

When you make a submenu, you are turning the parent menu item from a `Text` type, to a `Submenu` type. Menu items that expand into submenus don't usually have an action of their own. Can you find any examples of this in macOS? Can you explain a use case for the experience you're trying to deliver, and whether there's a workaround.

**Comment by ggrelet** [comment] 2021-03-15 22:26
Here is the description of a **BitBar** plugin of my own which highlights the new behavior that does not work anymore with xbar (no backward compatibility)

```
top1 >
--child *
top2 >
--child *
top3 >
--child *

and so on...
```

Tops are Reddit posts from [r/soccer](https://www.reddit.com/r/soccer/) with a filter on video content only. They have an `href` tag which redirects to the link of the video content (mostly hosted on streaming services).

Children always have the same text but also have an `href` tag which redirects to the actual reddit post (for comment reading 🤓).

Here is a gif of my BitBar plugin I'm describing, you should see what I mean (since you are from London I'm posting a Liverpool goal 😉):

![Enregistrement de l’écran 2021-03-15 à 22 59 20(3)](https://user-images.githubusercontent.com/10114131/111228544-b293cb00-85e4-11eb-88d1-006a45cd6ebf.gif)


> Menu items that expand into submenus don't usually have an action of their own.

The behavior you are describing here is incompatible with what I want, which used to work with BitBar. Maybe the behavior is intended, as you are suggesting. But I pushed this 'investigation' a little further. Consider this new python code:
```python
#!/usr/bin/env PYTHONIOENCODING=UTF-8 /usr/bin/python3

print("bug test")
print('---')
print("google.com | href='https://google.com/' color='#FF5700'")
print("--yahoo.com | href='https://yahoo.com/' color='#FF5700'")
print("----bing.com | href='https://bing.com/' color='#FF5700'")
```
It's the same as from my original post except that now I added orange color to the text to track down which of the menus/submenus have color. **Only the last children have the color added:**
<img width="408" alt="image" src="https://user-images.githubusercontent.com/10114131/111228995-714feb00-85e5-11eb-8280-a7a561b75cf6.png">

**I think only the leaves of the tree gets to have enriched text with `|`.** I think this should be considered a bug.

**Comment by leaanthony** [comment] 2021-03-16 07:55
I can't comment on the clicking of menus, but the styling of submenus should indeed be a thing. Thanks for raising this!

**Comment by matryer** [comment] 2021-03-16 09:38
@ggrelet If we can enable actions on submenu items I have nothing against it. @leaanthony Do you think it's possible?

**Comment by leaanthony** [comment] 2021-03-16 19:48
Must be 😃

**Comment by gzphreak** [comment] 2021-03-19 20:20
I'd like to +1 this. If it was unexpected behavior in BitBar it would be nice to clarify and support it in xbar. It's very useful to have actions on submenus.

**Comment by matryer** [comment] 2021-03-19 20:43
Thank you. Yeah—we’re sold. We’re gonna try and sort it out.

**Comment by gzphreak** [comment] 2021-04-02 17:05
@matryer It looks like this was fixed in the latest release. Thank you.

**Closed** 2021-04-02 20:35 UTC
Labels: bug, ♡ todo
