### ISSUE TITLE
Inline formatting using python

### ISSUE THREAD

**Issue by pnewell** [matryer/xbar#698] opened 2021-04-07 20:46 UTC
I wrote a xbar plugin using python and am having trouble getting inline styling to work. I have attempted some of the examples provided in other issue tickets, but those all seem to be shell and when I try them using python the whole thing is treated as a string (ansi is not turned into formatting).

For example:
`print(u'\u001b[34m blue \u001b[31m red | ansi=true')`

Results in:
<img width="152" alt="Screen Shot 2021-04-07 at 4 45 57 PM" src="https://user-images.githubusercontent.com/6485697/113931715-c9cb7000-97c0-11eb-96b3-fd251d5d100b.png">

**Comment by matryer** [comment] 2021-04-08 00:46
Thanks for reporting this @pnewell - we're working on it.

**Comment by matryer** [comment] 2021-04-08 00:47
Duplicate of #699

**Closed by matryer** 2021-04-08 00:47 UTC
Labels: duplicate duplicate
