### ISSUE TITLE
"terminal=true" not working?

### ISSUE THREAD

**Issue by Mikii67** [matryer/xbar#722] opened 2021-05-10 08:04 UTC
Hi. I am using version 2.0.42 on a Mac M1 with Big Sur 11.3.1,  and I cannot get "terminal=true" to work.

Is anybody else having the same issues?

**Comment by zverhope** [comment] 2021-05-18 01:29
Yep, I'm just making the move from BitBar to xbar now and am having the same issue with plugins that work well with BitBar.

**Comment by leaanthony** [comment] 2021-05-18 20:00
I'll check this out this week 👍

**Comment by matryer** [comment] 2021-05-21 11:55
Hey @Mikii67 and @zverhope - yeah this not yet working due to complications when implementing it.

The problem is, I wanted to use a template to allow people to customise which application this uses (BitBar only supported Terminal, but people like to use other terminals like iTerm 2 etc.)

**Comment by Mikii67** [comment] 2021-05-21 13:15
Thanks for letting us know, and once again thanks for there great app!

Michele

**Comment by Phocacius** [comment] 2021-06-04 09:45
As a workaround, it's possible to create an intermediate file that launches the terminal:

In the plugin file:
```sh
some entry | shell='/Users/xxx/bin/open_terminal.command'
```

open_terminal.command:
```sh
#/bin/bash

open -a "/Applications/Utilities/Terminal.app" "/the/file/you/actually/want/to/open"
```

**Comment by C4Wiz** [comment] 2021-08-24 11:45
@matryer will we see this fixed in a release anytime soon?

i am not interested in a workaround

**Comment by matryer** [comment] 2021-08-28 12:09
@C4Wiz Yes - see the [latest release](https://github.com/matryer/xbar/releases/tag/v2.1.5-beta)

**Comment by matryer** [comment] 2021-08-28 12:09
Duplicate of #680

**Closed by matryer** 2021-08-28 12:09 UTC
Labels: bug
