### ISSUE TITLE
templateImage doesn't update 

### ISSUE THREAD

**Issue by danielschonfeld** [matryer/xbar#789] opened 2021-11-01 15:36 UTC
Take for example Mustafa's coinbase prices script. If you change it to cycle through the different prices, with their different icons. The icon doesn't update, even though you specify a different templateImage

**Comment by danielschonfeld** [comment] 2021-11-01 15:37
seems like this is a duplicate of #717 - still a problem though

**Comment by matryer** [comment] 2022-01-04 11:04
duplicate of #717 - but yes, it's annoying.

**Closed by matryer** 2022-01-04 11:04 UTC
