### ISSUE TITLE
stop opening the plugin browser on startup

### ISSUE THREAD

**Issue by anisg** [matryer/xbar#695] opened 2021-04-06 22:07 UTC
once I setup my scripts and plugins, I don't really need to checkout the new plugins so if there can be an option to prevent the plugins browser to open on startup that would be great.

**Comment by MiqViq** [comment] 2021-04-07 08:29
This would be preferably managed by an entry in application prefs?
DoNotOpenPluginBrowserAtStartup = true
And app itself should also read prefs file in the global domain at /Library/Preferences/

**Comment by matryer** [comment] 2021-04-07 09:33
@anisg it should **not** open the plugin browser on startup. Can you tell us which version of xbar you're running, and on which operating system?

**Comment by MiqViq** [comment] 2021-04-07 13:40
I had this experience with M1 MBA13 and macOS Big Sur 11.2.3 20D91.
I will do further testing if this happens again with a fresh user account.

**Comment by anisg** [comment] 2021-04-09 19:05
![image](https://user-images.githubusercontent.com/17178399/114228810-486a0e00-9977-11eb-9d55-3993a5f37bfc.png)
maybe because it's the beta

**Comment by leaanthony** [comment] 2021-04-09 22:07
@MiqViq I have this exact setup and I can't reproduce 🤔

**Comment by bunnyhero** [comment] 2021-04-17 16:54
it just happened to me for the first time. it didn't happen the last few startups. i'm running 2.0.42-beta on big sur 11.2.3 (20D91) intel macbook pro. curious

**Comment by leaanthony** [comment] 2021-04-17 20:14
I can't guarantee it, but I think this might go away next release.

**Comment by leaanthony** [comment] 2021-04-20 21:08
Closing as duplicate of #687

**Comment by leaanthony** [comment] 2021-04-20 21:09
@bunnyhero just to confirm, what version OS are you running?

**Closed by leaanthony** 2021-04-20 21:08 UTC
Labels: bug

**Comment by bunnyhero** [comment] 2021-04-21 00:11
@leaanthony macOS Big Sur 11.2.3
