### ISSUE TITLE
Change default location of plugin folder

### ISSUE THREAD

**Issue by kudumi** [matryer/xbar#748] opened 2021-07-19 10:27 UTC
I sync plugins across multiple computers (e.g., dropbox), earlier version had an option "choose default plugin folder". It'll be great if we can bring it back? thanks

**Comment by sulrich** [comment] 2021-07-20 13:45
see also: #653

**Comment by matryer** [comment] 2021-08-28 12:00
Duplicate of #653

**Closed by matryer** 2021-08-28 12:00 UTC
Labels: duplicate duplicate
